version: '3.7'
services:
  app:
    container_name: vendas_rabbitmq
    tty: true
    image: maven:latest
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    ports:
      - 8081:8080
    command: bash -c "tail -f /dev/null"